language: node_js
branches:
  except:
    - gh-pages
stages:
  - lint
  - build
jobs:
  include:
    - stage: lint
      script:
        # Run linter
        - npm run lint
    - stage: build
      script:
        - npm run build
